---
name: Go Action
description: A GitHub Action written in Go.

inputs:
  delete:
    description: 'Delete the environment'
    required: false
    default: 'false'
  environment:
    description: 'Environment name'
    required: true
  repository:
    description: 'Repository name'
    required: true
  secrets:
    description: 'Secrets to set in the environment'
    required: false
    default: '{}'
  variables:
    description: 'Variables to set in the environment'
    required: false
    default: '{}'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.delete }}
    - ${{ inputs.environment }}
    - ${{ inputs.repository }}
    - ${{ inputs.secrets }}
    - ${{ inputs.variables }}
...