---
name: Go Action Example

on:
  repository_dispatch:
    types:
      - environment

jobs:
  manage_environment:
    name: "Manage Environment - ${{ github.event.client_payload.environment }} on ${{ github.event.client_payload.repository }}"
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        id: environment
        name: Run Go Action
        uses: dustindortch/go-action-rd@main
        with:
          delete: ${{ github.event.client_payload.delete || 'false' }}
          environment: ${{ github.event.client_payload.environment }}
          repository: ${{ github.event.client_payload.repository }}
          secrets: ${{ toJson(github.event.client_payload.secrets) || '{}' }}
          variables: ${{ toJson(github.event.client_payload.variables) || '{}' }}
...