---
name: Go Action Example

on:
  repository_dispatch:
    types:
      - environment

jobs:
  greet-me:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        id: environment
        name: Run Go Action
        uses: dustindortch/go-action@main
        with:
          delete: ${{ github.event.client_payload.delete || 'false' }}
          environment: ${{ github.event.client_payload.environment }}
          repository: ${{ github.event.client_payload.repository }}
          secrets: ${{ github.event.client_payload.secrets || '{}' }}
          variables: ${{ github.event.client_payload.variables || '{}' }}
...